### ISSUE TITLE
Add @babel/plugin-transform-react-jsx

### ISSUE THREAD

**Issue by antonio24073** [Eliav2/react-native-collapsible-view#1]
web app:

`Failed to compile
./node_modules/@eliav2/react-native-collapsible-view/index.js
SyntaxError: .../node_modules/@eliav2/react-native-collapsible-view/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (76:52):

  74 |   });
  75 | 
> 76 |   const TitleElement = typeof title === "string" ? <Text style={styles.TitleText}>{title}</Text> : title;
     |                                                    ^
  77 | 
  78 |   useEffect(() => {
  79 |     // this part is to trigger collapsible animation only after he has been fully mounted so animation would

Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.`

**Comment by Eliav2** [comment]
hey @antonio24073, thanks for opening this issue.
I would like to get some more info about this because I did not get it myself, and i want.
1. what version react-native you using?
2. do you use react-native-cli or expo-cli?

please help me reproduce this.

**Comment by antonio24073** [comment]
react-native-cli 0.63.2

Solved

./config/webpack.config.js line 421
`
                                plugins: [
                                    "@babel/plugin-transform-react-jsx",
                                    "@babel/plugin-proposal-class-properties",
                                    [
`
Execute:
`
echo "export const ViewPropTypes = { style: null };" >> ../node_modules/react-native-web/dist/index.js
`
you can create a bash file, add it to package.json to execute with npm

**Comment by Eliav2** [comment]
I don't understand you, friend, be more specific
