### ISSUE TITLE
How do I get the Chevron and text to be flex-start instead of center?

### ISSUE THREAD

**Issue by GollyJer** [Eliav2/react-native-collapsible-view#10]
I feel dumb I can't figure it out. Thanks.

**Comment by Eliav2** [comment]
```jsx
<CollapsibleView title="Basic Usage" touchableWrapperStyle={{alignItems:"start"}}></CollapsibleView>
```
![image](https://github.com/Eliav2/react-native-collapsible-view/assets/47307889/37f9c7a6-3635-4003-bca3-d8bcea3754f2)

**Comment by GollyJer** [comment]
Thanks @Eliav2. I swear I tried that. 🙃
For anyone playing along. It needs to be `flex-start`, not `start`.
