### ISSUE TITLE
Collapsible View Closed When I Pressed Button Inside it

### ISSUE THREAD

**Issue by ddikodroid** [Eliav2/react-native-collapsible-view#4]
![2021-04-08 10 47 44](https://user-images.githubusercontent.com/4207774/113965729-20d05400-9858-11eb-8279-77aff1bcbfe2.gif)

Like what I write in title, the collapsible view always closed automatically when I press a button inside it.
Expected Behaviour: Collapsible View still open

**Comment by hchen98** [comment]
It's unavoidable. When the collapse clicked, it seems like the entire dropdown content is acted clickable. So when click anywhere inside dropdown content, it triggers the collapse back. A simple solution I would do is to move that button outside collapsible component.

**Comment by Eliav2** [comment]
Hey friend! Please provide code snippets.
Its looks strange, because the clickable button event should be catched first(see nested collapsibles example)

**Comment by ddikodroid** [comment]
I'm sorry, but I can't provide code snippets because I didn't commit it.
